name = "brainsait-sbs-dynamic"
main = "src/index.ts"
compatibility_date = "2024-01-25"

[[d1_databases]]
binding = "DB"
database_name = "sbs_db"
database_id = "334fd7dc-3fa6-4f53-aa72-f515fbf28398"

[vars]
ENVIRONMENT = "development"
HEALTHCARE_API_URL = "https://brainsait-healthcare--fadil369.github.app"
OID_SERVICE_URL = "https://brainsait-oid-integr--fadil369.github.app"

[observability]
enabled = true
